Repository BETTER-iTER/Web, pull requests merged in 2024-02, with the labels that each got.

#153 Feat#150 QA 수정사항
  iTER/src/apis/Mypage.ts
  iTER/src/component/home/Review.tsx
  iTER/src/component/review/PreviewSimple.tsx
  iTER/src/component/review/Relation.tsx
  iTER/src/component/review/WriteUser.tsx
  iTER/src/component/search/Result.tsx
  iTER/src/component/signup/Nickname.tsx
  iTER/src/component/user/ProfileFlat.tsx
  iTER/src/constants/Jobs.ts
  iTER/src/pages/mypage/Follow.tsx
  iTER/src/pages/mypage/Index.tsx
  iTER/src/pages/mypage/Like.tsx
  iTER/src/pages/review/ReviewDetail.tsx
  iTER/src/pages/user/Profile.tsx
  iTER/src/types/Review.ts
Labels: 🚑 Fix

#160 Feat#159 검색결과 수정
  iTER/src/component/search/Result.tsx
Labels: 🚑 Fix

#158 Feat#155 회원정보 변경
  iTER/src/App.tsx
  iTER/src/apis/User.ts
  iTER/src/component/home/News.tsx
  iTER/src/component/home/Review.tsx
  iTER/src/component/user/ProfileFlat.tsx
  iTER/src/pages/Home.tsx
  iTER/src/pages/mypage/EditProfile.tsx
  iTER/src/pages/mypage/Interest.tsx
  iTER/src/pages/mypage/Setting.tsx
Labels: 📬 API

#161 Feat#152 팔로우 기능 연동
  iTER/src/component/common/Button.tsx
Labels: 📬 API

#162 Feat#157 리뷰등록 이미지 처리
  iTER/src/component/common/Button.tsx
  iTER/src/component/review/ImageUpload.tsx
  iTER/src/component/review/SelectBox.tsx
  iTER/src/context/DataContext.tsx
  iTER/src/pages/review/Compelete.tsx
  iTER/src/pages/review/ReviewStar.tsx
  iTER/src/pages/review/WriteDetail.tsx
  node_modules/eslint-plugin-react-hooks/node_modules/.bin/eslint 2
  node_modules/eslint-plugin-react-hooks/node_modules/.bin/eslint 3
  node_modules/postcss/node_modules/.bin/nanoid 2
  node_modules/postcss/node_modules/.bin/nanoid 3
  node_modules/vite/node_modules/.bin/esbuild 2
  node_modules/vite/node_modules/.bin/esbuild 3
  node_modules/vite/node_modules/.bin/rollup 2
  node_modules/vite/node_modules/.bin/rollup 3
Labels: ✨Feat, 📬 API

#168 Feat#137 뉴스 스와이프 추가
  iTER/src/component/home/News.tsx
Labels: ✨Feat
