Repository BETTER-iTER/Web, pull requests merged in 2024-01, with the labels that each got.

#115 Feat#114 리뷰 삭제 연동
  iTER/src/apis/Common.ts
  iTER/src/apis/Review.ts
  iTER/src/component/common/Bottom.tsx
  iTER/src/component/common/Category.tsx
  iTER/src/component/common/InputSelect.tsx
  iTER/src/component/home/Review.tsx
  iTER/src/component/review/DetailReview.tsx
  iTER/src/component/review/Relation.tsx
  iTER/src/component/review/ReviewImage.tsx
  iTER/src/component/review/StarRating.tsx
  iTER/src/component/review/StarRatingShow.tsx
  iTER/src/component/search/Category.tsx
  iTER/src/component/search/ListItem.tsx
  iTER/src/component/search/Result.tsx
  iTER/src/component/signup/Interest.tsx
  iTER/src/component/signup/Job.tsx
  iTER/src/component/user/ProfileSimple.tsx
  iTER/src/constants/Jobs.ts
  iTER/src/constants/Store.ts
  iTER/src/pages/Home.tsx
  iTER/src/pages/Login.tsx
  iTER/src/pages/mypage/EditProfile.tsx
  iTER/src/pages/review/ReviewDetail.tsx
  iTER/src/pages/signup/SignupAdditional.tsx
  iTER/src/pages/signup/SignupComplete.tsx
  iTER/src/types/Review.ts
  iTER/src/types/User.ts
  iTER/src/types/auth.ts
Labels: 📬 API

#126 Feat#125 스타일 수정
  iTER/src/apis/Mypage.ts
  iTER/src/component/common/Button.tsx
  iTER/src/component/home/News.tsx
  iTER/src/component/layout/Footer.tsx
  iTER/src/component/review/PreviewSimple.tsx
  iTER/src/component/search/ListItem.tsx
  iTER/src/component/search/Result.tsx
  iTER/src/component/user/ProfileFlat.tsx
  iTER/src/component/user/ProfileSimple.tsx
  iTER/src/constants/NavRouter.ts
  iTER/src/pages/Home.tsx
  iTER/src/pages/mypage/Follow.tsx
  iTER/src/pages/mypage/Index.tsx
  iTER/src/pages/mypage/Like.tsx
  iTER/src/pages/review/ReviewDetail.tsx
  iTER/src/types/Review.ts
  iTER/src/types/User.ts
  iTER/src/utills/PrivateRoute.tsx
Labels: 🎨 Design

#128 Feat#111
  iTER/package-lock.json
  iTER/src/assets/icon/HeartFill.svg
  iTER/src/component/common/LikeSort.tsx
  iTER/src/component/review/DetailReview.tsx
  iTER/src/context/DataContext.tsx
  iTER/yarn.lock
Labels: ✨Feat, 📬 API

#129 Feat#112
  iTER/package-lock.json
  iTER/src/component/Font.ts
  iTER/src/component/common/Bottom.tsx
  iTER/src/component/common/Button.tsx
  iTER/src/component/common/CommentSort.tsx
  iTER/src/component/common/Input.tsx
  iTER/src/component/common/LoginInput.tsx
  iTER/src/component/common/Modal.tsx
  iTER/src/component/review/DetailReview.tsx
  iTER/yarn.lock
  node_modules/@babel/helper-compilation-targets/node_modules/.bin/browserslist 4
  node_modules/@vitejs/plugin-react/node_modules/.bin/vite 4
  node_modules/@vitejs/plugin-react/node_modules/.bin/vite 5
  node_modules/cross-spawn/node_modules/.bin/node-which 4
  node_modules/cross-spawn/node_modules/.bin/node-which 5
  node_modules/eslint-plugin-prettier/node_modules/.bin/eslint 4
  node_modules/eslint-plugin-prettier/node_modules/.bin/eslint 5
  node_modules/eslint-plugin-prettier/node_modules/.bin/prettier 4
  node_modules/eslint-plugin-prettier/node_modules/.bin/prettier 5
  node_modules/espree/node_modules/.bin/acorn 4
  node_modules/espree/node_modules/.bin/acorn 5
  node_modules/update-browserslist-db/node_modules/.bin/browserslist 4
  node_modules/update-browserslist-db/node_modules/.bin/browserslist 5
Labels: ✨Feat, 📬 API

#132 Feat#130
  iTER/src/apis/Review.ts
  iTER/src/apis/auth.ts
  iTER/src/assets/icon/ArrowDown.svg
  iTER/src/component/common/Bottom.tsx
  iTER/src/component/common/Button.tsx
  iTER/src/component/common/Category.tsx
  iTER/src/component/common/Modal.tsx
  iTER/src/component/home/Review.tsx
  iTER/src/component/review/DetailReview.tsx
  iTER/src/component/review/PreviewSimple.tsx
  iTER/src/component/review/Relation.tsx
  iTER/src/component/search/ListItem.tsx
  iTER/src/component/search/Result.tsx
  iTER/src/constants/Category.ts
  iTER/src/pages/Home.tsx
  iTER/src/pages/Notification.tsx
  iTER/src/pages/Search.tsx
  iTER/src/pages/review/CheckCategory.tsx
  iTER/src/pages/review/ReviewDetail.tsx
  iTER/src/pages/signup/SignUp.tsx
  iTER/src/types/Home.ts
  iTER/src/types/Review.ts
Labels: 🚑 Fix, 🎨 Design

#138 Feat#133
  iTER/src/apis/Review.ts
  iTER/src/component/review/SelectBox.tsx
  iTER/src/component/search/ListItem.tsx
  iTER/src/pages/Onboading.tsx
Labels: 📬 API

#141 Feat#134 회원가입 오류 처리 수정
  iTER/src/apis/auth.ts
  iTER/src/component/signup/Nickname.tsx
  iTER/src/component/signup/Timer.tsx
  iTER/src/pages/signup/SignUp.tsx
Labels: 🚑 Fix

#144 리뷰 상세 조회 스크랩 api 연동
  iTER/src/assets/icon/ScrapFill.svg
  iTER/src/component/review/DetailReview.tsx
Labels: 📬 API

#146 인풋 이슈 수정
  iTER/src/component/common/CommentSort.tsx
  iTER/src/component/common/Input.tsx
Labels: ✨Feat

#148 Feat#147 검색기능 수정
  iTER/src/apis/Review.ts
  iTER/src/component/search/ListItem.tsx
  iTER/src/component/search/Result.tsx
  iTER/src/pages/Home.tsx
  iTER/src/pages/Search.tsx
Labels: 🔨 Refactor
